In [13]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.optim.lr_scheduler import CosineAnnealingLR
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from itertools import product
from dataclasses import dataclass
from collections import namedtuple, defaultdict
from tasks.markov import *
from models.base_models import *
from models.pos_encoder import *
from models.forward_tracer import *
from tasks.test_markov import *
from config import *
from train import *
import figures.plot as plot
from figures.ood_plots import *
from util import *
import seaborn as sns
import torch.utils.benchmark as benchmark
from tqdm.notebook import tqdm, trange
import os
import re

from figures.head_view import *

torch.set_printoptions(precision=3, sci_mode=False)

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [4]:
SEQ_LEN, VOC_SIZE, BATCH_SIZE, alpha = 128, 5, 32, 1
pos_enc="rotary"
hidden_dim=128
mlp_layers=None
epochs=10000
num_layers=2

flash = False
    
if pos_enc in ["rotary", "abs"]:
    flash = True

if mlp_layers is None:
    mlp_layers = [i for i in range(num_layers)]
    
mlp = [False] * num_layers
for i in mlp_layers:
    mlp[i] = True 
mlp = tuple(mlp)

config = Config(
        emb_dim=hidden_dim,
        num_layers=num_layers,
        num_heads=tuple([1]*num_layers),
        identity_query=False,
        seq_len=SEQ_LEN,
        vocab_size=VOC_SIZE,
        batch_size=BATCH_SIZE,
        num_epochs=epochs,
        eval_iter=1000,
        pos_enc=pos_enc,
        pos_max_len=SEQ_LEN,
        get_attn=500,
        get_checkpoints=200,
        mlp=mlp,
        activation=mlp,
        flash=flash, # Use rotary
        ff_dim=hidden_dim,
        layer_norm=False,
        ngram=2,
        learning_rate=1e-4,
        task_name="icl-mc"
    )

sampler_config = MarkovSamplerConfig(seq_len=SEQ_LEN, vocab_size=VOC_SIZE, order=1, alpha=alpha,
                                     batch_size=BATCH_SIZE, task_name="icl-mc")

model = Transformer(config)

In [15]:
get_layers(model)

ModuleList(
  (0-1): 2 x TFBlock(
    (MHA): MultiHeadAttention(
      (query): Linear(in_features=128, out_features=128, bias=False)
      (key): Linear(in_features=128, out_features=128, bias=False)
      (value): Linear(in_features=128, out_features=128, bias=False)
      (out): Linear(in_features=128, out_features=128, bias=False)
    )
    (ln1): Identity()
    (mlp): Sequential(
      (0): Linear(in_features=128, out_features=128, bias=True)
      (1): ReLU()
      (2): Linear(in_features=128, out_features=128, bias=True)
    )
    (ln2): Identity()
  )
)

In [1]:
import numpy as np

In [25]:
n = 1000
a = np.zeros(n)
b = np.zeros(n)
p = np.zeros(n)
a[0] = 0.1
b[0] = 0.3
p[0] = a[0]+b[0]
y = 0.7
eta = 0.001
for t in range(1,n):
    a[t] = a[t-1] + (y-p[t-1]) / (p[t-1]*(1-p[t-1])) * eta
    b[t] = b[t-1] + (y-p[t-1]) / (p[t-1]*(1-p[t-1])) * eta
    p[t] = a[t] + b[t]

In [26]:
a

array([0.1       , 0.10125   , 0.10248704, 0.10371136, 0.10492322,
       0.10612283, 0.10731043, 0.10848623, 0.10965045, 0.11080327,
       0.11194491, 0.11307555, 0.11419537, 0.11530456, 0.11640329,
       0.11749172, 0.11857002, 0.11963834, 0.12069685, 0.12174568,
       0.12278499, 0.12381492, 0.12483559, 0.12584716, 0.12684974,
       0.12784346, 0.12882845, 0.12980483, 0.1307727 , 0.1317322 ,
       0.13268342, 0.13362648, 0.13456148, 0.13548852, 0.13640771,
       0.13731914, 0.13822291, 0.13911912, 0.14000785, 0.14088919,
       0.14176324, 0.14263008, 0.14348978, 0.14434244, 0.14518814,
       0.14602694, 0.14685894, 0.14768419, 0.14850279, 0.1493148 ,
       0.15012029, 0.15091932, 0.15171198, 0.15249832, 0.15327841,
       0.15405232, 0.1548201 , 0.15558182, 0.15633755, 0.15708733,
       0.15783123, 0.1585693 , 0.15930161, 0.1600282 , 0.16074913,
       0.16146446, 0.16217424, 0.16287852, 0.16357734, 0.16427077,
       0.16495885, 0.16564162, 0.16631914, 0.16699145, 0.16765

In [23]:
p

array([0.4       , 0.4025    , 0.40497408, ..., 0.7       , 0.7       ,
       0.7       ])

In [24]:
b

array([0.3       , 0.30125   , 0.30248704, ..., 0.45      , 0.45      ,
       0.45      ])