In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.optim.lr_scheduler import CosineAnnealingLR
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from itertools import product
from dataclasses import dataclass
from collections import namedtuple, defaultdict
from tasks.markov import *
from models.base_models import *
from models.pos_encoder import *
from models.forward_tracer import *
from tasks.test_markov import *
from config import *
from train import *
import figures.plot as plot
from figures.ood_plots import *
from util import *
import seaborn as sns
import torch.utils.benchmark as benchmark
from tqdm.notebook import tqdm, trange
import os
import re

from figures.head_view import *

torch.set_printoptions(precision=3, sci_mode=False)

%load_ext autoreload
%autoreload 2

In [8]:
yaml_path = "config.yaml"
sampler_config = MarkovSamplerConfig()
sampler_config.update_from_yaml(yaml_path)
sampler = BiettiTask(sampler_config)
sampler.print_trans_mat()

,0,1,2
00,0.160,0.792,0.048
01,0.719,0.183,0.098
02,0.806,0.091,0.103
10,0.646,0.256,0.098
11,0.124,0.603,0.273
12,0.414,0.008,0.579
20,0.182,0.713,0.105
21,0.310,0.038,0.653
22,0.360,0.501,0.139


In [16]:
ngram_learner = mixed_ngramLearner(sampler_config, 2, False)

In [17]:
batch, mask = sampler.generate(mode="test")
batch = batch.squeeze(0)
mask = mask.squeeze(0)
ngram_learner.update(batch, mask)
ngram_learner.loss(batch, mask)

tensor(0.606, device='cuda:0')

In [6]:
ngram_learner.print_trans_mat()

tensor([0.256, 0.431, 0.313])


In [7]:
batch, mask = sampler.generate(mode="train")
batch = batch.squeeze(0)
mask = mask.squeeze(0)
ngram_learner.update(batch, mask)
ngram_learner.predict(batch, mask)

tensor([[[0.256, 0.431, 0.313],
         [0.256, 0.431, 0.313],
         [0.256, 0.431, 0.313],
         ...,
         [0.256, 0.431, 0.313],
         [0.256, 0.431, 0.313],
         [0.256, 0.431, 0.313]],

        [[0.256, 0.431, 0.313],
         [0.256, 0.431, 0.313],
         [0.256, 0.431, 0.313],
         ...,
         [0.256, 0.431, 0.313],
         [0.256, 0.431, 0.313],
         [0.256, 0.431, 0.313]],

        [[0.256, 0.431, 0.313],
         [0.256, 0.431, 0.313],
         [0.256, 0.431, 0.313],
         ...,
         [0.256, 0.431, 0.313],
         [0.256, 0.431, 0.313],
         [0.256, 0.431, 0.313]],

        ...,

        [[0.256, 0.431, 0.313],
         [0.256, 0.431, 0.313],
         [0.256, 0.431, 0.313],
         ...,
         [0.256, 0.431, 0.313],
         [0.256, 0.431, 0.313],
         [0.256, 0.431, 0.313]],

        [[0.256, 0.431, 0.313],
         [0.256, 0.431, 0.313],
         [0.256, 0.431, 0.313],
         ...,
         [0.256, 0.431, 0.313],
         [0.

In [31]:
batch

tensor([[0, 2, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
         0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 2, 1, 0,
         1, 0, 1, 0, 0, 2, 1, 0, 2, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
         2, 1, 0, 0, 1, 0, 1, 0, 2, 0, 2, 1, 0, 0, 0, 0, 2, 2, 2, 0, 1, 0, 1, 0,
         2, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 1, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0,
         1, 0, 0, 0, 0, 0, 2, 0, 0, 2, 1, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
         1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 0, 0, 1, 0, 1, 0, 1, 0, 2, 0,
         1, 0, 2, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 2, 1, 0,
         2, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 2, 2, 2, 1, 0, 1, 0,
         2, 1, 0, 2, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 2, 1]])

In [36]:
mask

tensor([[0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
         0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
         0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
         0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
         1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
         0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
         0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
         0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]])

In [7]:
random_prob_est = ngram_learner.random_transition / ngram_learner.random_transition.sum(dim=-1, keepdim=True)
random_prob_est

tensor([[[nan, nan, nan],
         [nan, nan, nan],
         [0., 1., 0.]]])

In [212]:
mask[:,11]

tensor([1], device='cuda:0')

In [183]:
mask.shape

torch.Size([1, 256])

In [35]:
batch, mask, triggers, _ = sampler.generate(mode="testing")
batch = batch.reshape(2,-1)
mask = mask.reshape(2,-1)
mask = mask > 0
batch_stride = torch.as_strided(batch, 
                                size=(1, 256 - 2, 2), 
                                stride=(batch.stride(0), batch.stride(1), batch.stride(1))).squeeze(0)

In [31]:
matches = (batch_stride == torch.tensor([0,0],device="cuda")).all(dim=-1)
indices = torch.nonzero(matches, as_tuple=False).squeeze()

In [38]:
torch.isin(torch.tensor([0,0],device="cuda"), triggers).any()

tensor(False, device='cuda:0')

In [94]:
t = 0
ngram_learner.trans_mat_est.index_put_((state_indices[~mask[:,t],t], next_states[~mask[:,t],t]), values[~mask[:,t]], accumulate=True)

tensor([[0.600, 0.600, 0.600],
        [0.600, 0.600, 0.600],
        [0.600, 0.600, 0.600],
        [0.600, 0.600, 0.600],
        [0.600, 0.600, 0.600],
        [0.600, 1.600, 0.600],
        [0.600, 1.600, 0.600],
        [0.600, 0.600, 0.600],
        [0.600, 0.600, 0.600]], device='cuda:0')

In [97]:
(state_indices[~mask[:,t],t], next_states[~mask[:,t],t])

(tensor([5, 6], device='cuda:0'), tensor([1, 1], device='cuda:0'))