In [11]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
from itertools import product
from tasks.markov import *
from models.base_models import *
from models.forward_tracer import *
from config import *
from train import *
import figures.plot as plot
from figures.ood_plots import *
from probe_util import *
import seaborn as sns
import torch.utils.benchmark as benchmark
from tasks.random_distributions import *
from tqdm.notebook import tqdm, trange
import os
import re

from figures.head_view import *
from config import get_config

torch.set_printoptions(precision=3, sci_mode=False)

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [15]:
config = get_config()
sampler = FRMarkovSampler(config)
batch, mask = sampler.generate(mode="copy", num_samples=1)
batch[0][torch.nonzero(mask==1)[:,1]+1]

tensor([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3], device='cuda:0')

In [4]:
nlr = NoisyLinearRegression(
    n_tasks = 2,
    n_dims = 8,
    n_points = 2,
    batch_size = 2,
    data_seed = 100,
    task_seed = 101,
    noise_seed = 102,
    data_scale = 1.0,
    task_scale = 1.0,
    noise_scale = 0.5,
)

In [12]:
data, tasks, targets = nlr.sample_batch(0)
seq = to_seq(data, targets)

In [13]:
seq

tensor([[[ 0.000,  0.127,  1.356,  0.563, -0.104, -0.357,  0.392, -0.680,
           0.241],
         [ 0.725,  0.000,  0.000,  0.000,  0.000,  0.000,  0.000,  0.000,
           0.000],
         [ 0.000,  0.470,  1.243,  0.540, -1.145, -1.459, -1.628,  0.383,
          -0.172],
         [-2.102,  0.000,  0.000,  0.000,  0.000,  0.000,  0.000,  0.000,
           0.000]],

        [[ 0.000, -3.190,  1.591, -0.025, -0.847,  0.029, -0.572, -1.255,
           0.049],
         [ 0.054,  0.000,  0.000,  0.000,  0.000,  0.000,  0.000,  0.000,
           0.000],
         [ 0.000,  1.170, -0.541, -0.712,  0.058,  0.626, -1.774, -0.221,
           2.747],
         [ 3.189,  0.000,  0.000,  0.000,  0.000,  0.000,  0.000,  0.000,
           0.000]]])

In [60]:
torch.Size([2])

torch.Size([2])

In [121]:
D = RandomHotDistribution(num_states=7, card=2)
D.sample([5])

tensor([[0.500, 0.000, 0.000, 0.000, 0.000, 0.500, 0.000],
        [0.000, 0.000, 0.500, 0.000, 0.000, 0.000, 0.500],
        [0.500, 0.500, 0.000, 0.000, 0.000, 0.000, 0.000],
        [0.000, 0.000, 0.000, 0.000, 0.500, 0.000, 0.500],
        [0.500, 0.500, 0.000, 0.000, 0.000, 0.000, 0.000]])

In [122]:
H = D.estimate_entropy()
print(f"Estimated entropy: {H:.4f} nats")

Estimated entropy: 3.0409 nats


In [46]:
yaml_path = "config.yaml"
sampler_config = MarkovSamplerConfig()
sampler_config.update_from_yaml(yaml_path)
sampler = FRMarkovSampler(sampler_config)
sampler.print_trans_mat()

,0,1,2,3,4,5,6,7,8,9
0,0.000,0.367,0.004,0.142,0.001,0.005,0.000,0.461,0.007,0.013
1,0.001,0.000,0.003,0.001,0.007,0.938,0.002,0.039,0.007,0.001
2,0.062,0.091,0.000,0.696,0.000,0.000,0.029,0.122,0.000,0.000
3,0.013,0.171,0.132,0.515,0.001,0.096,0.000,0.000,0.000,0.073
4,0.022,0.270,0.117,0.051,0.380,0.032,0.001,0.006,0.010,0.111
5,0.190,0.000,0.000,0.008,0.000,0.001,0.000,0.007,0.793,0.000
6,0.000,0.023,0.010,0.000,0.233,0.124,0.002,0.246,0.345,0.017
7,0.000,0.010,0.011,0.018,0.016,0.000,0.873,0.026,0.046,0.000
8,0.001,0.000,0.055,0.492,0.296,0.008,0.000,0.106,0.002,0.040
9,0.002,0.060,0.754,0.000,0.000,0.000,0.016,0.075,0.092,0.000


In [50]:
batch, mask, trigger, probs = sampler.generate(mode="testing")

In [18]:
batch[0]

tensor([2, 4, 4, 4, 3, 2, 0, 3, 0, 0, 2, 1, 4, 3, 2, 0, 2, 3, 2, 2, 0, 3, 1, 4,
        4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 4, 3, 3, 3, 3,
        4, 4, 2, 1, 4, 1, 4, 4, 2, 3, 3, 3, 4, 0, 4, 0, 2, 3, 2, 2, 1, 4, 1, 4,
        1, 4, 4, 2, 3, 4, 0, 3, 0, 2, 0, 3, 3, 4, 2, 3, 2, 2, 1, 4, 1, 4, 1, 4,
        1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 4, 1, 4, 4, 2, 4, 3, 4, 2, 4, 4, 3, 3, 3,
        3, 2, 4, 3, 4, 2, 1, 4], device='cuda:0')

In [52]:
states = torch.as_strided(batch, 
                          size=(batch.size(0), batch.size(1) - 2, 2), 
                          stride=(batch.stride(0), batch.stride(1), batch.stride(1)))  # (B, T-O, O)
ind = 0
states[ind][mask[ind][:-2]==1]

tensor([[8, 5],
        [8, 2],
        [8, 5],
        [8, 5],
        [8, 5],
        [8, 5],
        [8, 2],
        [8, 5],
        [8, 5],
        [8, 5],
        [8, 2],
        [8, 5],
        [8, 2],
        [8, 5],
        [8, 5],
        [8, 2],
        [8, 2],
        [8, 5],
        [8, 2],
        [8, 5],
        [8, 2],
        [8, 2],
        [8, 2],
        [8, 2],
        [8, 2],
        [8, 5],
        [8, 2],
        [8, 5],
        [8, 2],
        [8, 5],
        [8, 5],
        [8, 2],
        [8, 2],
        [8, 5],
        [8, 5],
        [8, 2],
        [8, 2],
        [8, 5],
        [8, 5],
        [8, 2],
        [8, 5],
        [8, 5],
        [8, 2]], device='cuda:0')

In [16]:
ngram_learner = mixed_ngramLearner(sampler_config, 2, False)

In [17]:
batch, mask = sampler.generate(mode="test")
batch = batch.squeeze(0)
mask = mask.squeeze(0)
ngram_learner.update(batch, mask)
ngram_learner.loss(batch, mask)

tensor(0.606, device='cuda:0')

In [2]:
import pymc as pm
import numpy as np
import arviz as az

# Simulated data
X = np.random.randn(100, 2)
y = X @ np.array([2.0, -1.0]) + np.random.randn(100)
X_new = np.random.randn(10, 2)

with pm.Model() as model:
    # Priors
    beta = pm.Normal("beta", mu=0, sigma=5, shape=2)
    sigma = pm.HalfNormal("sigma", sigma=1)

    # Likelihood
    mu = pm.math.dot(X, beta)
    y_obs = pm.Normal("y_obs", mu=mu, sigma=sigma, observed=y)

    # Sampling
    trace = pm.sample(1000, return_inferencedata=True)

# Extract posterior samples as arrays
beta_samples = trace.posterior["beta"].stack(sample=("chain", "draw")).values.T  # shape (n_samples, 2)
sigma_samples = trace.posterior["sigma"].stack(sample=("chain", "draw")).values.flatten()  # shape (n_samples,)

# Compute predicted means: shape (n_samples, n_test)
mu_pred = X_new @ beta_samples.T

# Sample from predictive distribution
# Shape: (n_samples, n_test)
y_pred_samples = np.random.normal(loc=mu_pred, scale=sigma_samples[:, np.newaxis])

# Each row corresponds to one posterior sample's prediction over X_new
# You can get predictive mean, intervals, etc.
predictive_mean = y_pred_samples.mean(axis=0)
predictive_std = y_pred_samples.std(axis=0)

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [beta, sigma]


Output()

Sampling 4 chains for 1_000 tune and 1_000 draw iterations (4_000 + 4_000 draws total) took 16 seconds.


ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (10, 4000) and arg 1 with shape (4000, 1).